export type Source = {
  id: string;
  domain: "Scholarships" | "Education" | "Employment" | "Benefits" | "Identity and documents" | "Finance and tax" | "Housing and food" | "Transport" | "Health insurance";
  effectiveDate: string;
  text: string;
  title: string;
  url: string;
};

export const sources: Source[] = [
  {
    id: "national-scholarship-portal",
    domain: "Scholarships",
    effectiveDate: "2026-08-06",
    title: "National Scholarship Portal",
    url: "https://scholarships.gov.in/",
    text: "The National Scholarship Portal is the Government of India portal for scholarship application services. Applicants should use the current portal notices, scheme information, eligibility conditions, timelines, and required-document guidance before applying.",
  },
  {
    id: "myscheme",
    domain: "Benefits",
    effectiveDate: "2026-08-06",
    title: "myScheme",
    url: "https://www.myscheme.gov.in/",
    text: "myScheme is a Government of India platform that helps people discover schemes and directs them to official application information. Scheme requirements, application availability, and eligibility can change, so users should verify details on the linked official page.",
  },
  {
    id: "pmjay",
    domain: "Health insurance",
    effectiveDate: "2026-08-06",
    title: "Ayushman Bharat PM-JAY",
    url: "https://pmjay.gov.in/",
    text: "Ayushman Bharat Pradhan Mantri Jan Arogya Yojana provides official information about the scheme, beneficiary services, and help channels. Coverage and beneficiary status must be verified through official PM-JAY tools or authorised support, not inferred from a chat response.",
  },
  {
    id: "nha-beneficiary",
    domain: "Health insurance",
    effectiveDate: "2026-08-06",
    title: "National Health Authority beneficiary resources",
    url: "https://nha.gov.in/",
    text: "The National Health Authority publishes official PM-JAY resources and programme information. Users seeking hospitalisation coverage or beneficiary support should rely on current National Health Authority and PM-JAY channels for confirmation.",
  },
  {
    id: "national-career-service",
    domain: "Benefits",
    effectiveDate: "2026-08-06",
    title: "National Career Service",
    url: "https://www.ncs.gov.in/",
    text: "National Career Service provides official employment-related information, including job-search, career guidance, and employer services. Users should review current service requirements and notices on the official portal.",
  },
  {
    id: "e-shram",
    domain: "Benefits",
    effectiveDate: "2026-08-06",
    title: "e-Shram",
    url: "https://eshram.gov.in/",
    text: "e-Shram provides official information for unorganised workers. Registration, worker records, and related services require verification through the current official e-Shram portal and authorised support channels.",
  },
  {
    id: "pm-kisan",
    domain: "Benefits",
    effectiveDate: "2026-08-06",
    title: "PM-KISAN",
    url: "https://pmkisan.gov.in/",
    text: "PM-KISAN publishes official programme information, beneficiary resources, and service notices for eligible farmer households. Current status and programme requirements must be verified through the official PM-KISAN portal.",
  },
  {
    id: "digilocker",
    domain: "Benefits",
    effectiveDate: "2026-08-06",
    title: "DigiLocker",
    url: "https://www.digilocker.gov.in/",
    text: "DigiLocker is an official digital document wallet and issuer platform. Users should access their documents and issuer records through the official service and confirm document requirements with the requesting organisation.",
  },
  {
    id: "ugc",
    domain: "Education",
    effectiveDate: "2026-08-06",
    title: "University Grants Commission",
    url: "https://www.ugc.gov.in/",
    text: "The University Grants Commission publishes official higher-education notices, regulations, and institutional information. Students should use current UGC notices and their institution's official communication for academic requirements.",
  },
  {
    id: "aicte",
    domain: "Education",
    effectiveDate: "2026-08-06",
    title: "All India Council for Technical Education",
    url: "https://www.aicte-india.org/",
    text: "AICTE publishes official information for technical education, approved institutions, programmes, and notices. Applicants should verify programme and institutional details on current official records.",
  },
  {
    id: "swayam",
    domain: "Education",
    effectiveDate: "2026-08-06",
    title: "SWAYAM",
    url: "https://swayam.gov.in/",
    text: "SWAYAM is an official online learning platform with courses from participating institutions. Course availability, credits, examinations, and certificates should be confirmed on the current course page.",
  },
  {
    id: "apprenticeship-india",
    domain: "Employment",
    effectiveDate: "2026-08-06",
    title: "Apprenticeship India",
    url: "https://www.apprenticeshipindia.gov.in/",
    text: "Apprenticeship India provides official apprenticeship information, opportunities, and portal services. Candidate eligibility, openings, and application requirements require confirmation on the official portal.",
  },
  {
    id: "epfo",
    domain: "Employment",
    effectiveDate: "2026-08-06",
    title: "Employees' Provident Fund Organisation",
    url: "https://www.epfindia.gov.in/",
    text: "EPFO provides official provident-fund member, employer, pension, and claim information. Account status, claims, and service eligibility must be verified through official EPFO channels.",
  },
  {
    id: "esic",
    domain: "Employment",
    effectiveDate: "2026-08-06",
    title: "Employees' State Insurance Corporation",
    url: "https://www.esic.gov.in/",
    text: "ESIC publishes official information about employee insurance services and benefits. Insured-person status, service access, and benefit conditions require verification through ESIC.",
  },
  {
    id: "uidai",
    domain: "Identity and documents",
    effectiveDate: "2026-08-06",
    title: "Unique Identification Authority of India",
    url: "https://uidai.gov.in/",
    text: "UIDAI provides official Aadhaar enrolment, update, authentication, and help information. Identity details and Aadhaar services should be handled only through official UIDAI channels.",
  },
  {
    id: "pfrda",
    domain: "Finance and tax",
    effectiveDate: "2026-08-06",
    title: "Pension Fund Regulatory and Development Authority",
    url: "https://www.pfrda.org.in/",
    text: "PFRDA publishes official pension-system information and regulatory resources. Pension account actions, investment choices, and service requests require confirmation through authorised pension channels.",
  },
  {
    id: "income-tax",
    domain: "Finance and tax",
    effectiveDate: "2026-08-06",
    title: "Income Tax Department e-Filing",
    url: "https://www.incometax.gov.in/iec/foportal/",
    text: "The Income Tax Department e-Filing portal provides official tax filing, refund, and taxpayer service information. Tax positions, filing duties, and deadlines require review of current official guidance or qualified tax advice.",
  },
  {
    id: "pmay",
    domain: "Housing and food",
    effectiveDate: "2026-08-06",
    title: "Pradhan Mantri Awas Yojana Urban",
    url: "https://pmay-urban.gov.in/",
    text: "Pradhan Mantri Awas Yojana Urban provides official housing-scheme information and notices. Programme availability, beneficiary status, and application conditions must be verified through current official channels.",
  },
  {
    id: "nfsa",
    domain: "Housing and food",
    effectiveDate: "2026-08-06",
    title: "National Food Security Act Portal",
    url: "https://nfsa.gov.in/",
    text: "The National Food Security Act portal provides official food-security programme information and state-linked resources. Entitlement and ration-card status require verification through the relevant state authority.",
  },
  {
    id: "parivahan",
    domain: "Transport",
    effectiveDate: "2026-08-06",
    title: "Parivahan Sewa",
    url: "https://parivahan.gov.in/",
    text: "Parivahan Sewa provides official vehicle, driving-licence, and transport-service information. Application status, document requirements, fees, and appointments require confirmation through the appropriate official transport service.",
  },
];
